SELECT
    date(ZOBJECT.ZSTARTDATE+978307200,'UNIXEPOCH', 'LOCALTIME') as "DATE",
    round(sum(ZOBJECT.ZENDDATE-ZOBJECT.ZSTARTDATE) / 3600.0, 3 ) as "TOTAL_USAGE_PER_DAY_IN_HOURS"
FROM
    ZOBJECT 
WHERE
    ZSTREAMNAME = "/display/isBacklit"
GROUP BY
    DATE
ORDER BY
    DATE DESC;
